### ISSUE TITLE
请问和FeTrIL等方法的对比实验代码可以分享一下么，谢谢

### ISSUE THREAD

**Issue by 1259666087** [zhoujiahuan1991/CVPR2024-FCS#2]
您好我在看论文的时候发现实验的准确率中的其他方法和原论文有些出入，想了解一下您的实验设计，谢谢

**Comment by qiweili00** [comment]
Thanks for your interest in our work!

Some comparison methods (SSRE, FeTrIL) used the average accuracy as the evaluation metric. Following PASS, we adopt final accuracy (average accuracy of all the classes that have already been learned after the last task), which we think is more reasonable for incremental learning. Due to the knowledge forgetting and the increase in class numbers, the accuracy tends to decrease after each stage. Thus the final accuracy is lower than the average accuracy. 

We reimplement the comparison methods with their official code, such as [FeTrIL](https://github.com/GregoirePetit/FeTrIL).
